### ISSUE TITLE
Big-O complexity and methods to speed up?

### ISSUE THREAD

**Issue by thinhong** [AMenezes97/serosim#1]
Dear Arthur,

Thank you so much for developing an excellent R package. I am currently planning to use it for my research. However, when I tried the simple example provided with a population of 10,000, I noticed a considerable slowdown (>1 hour and it has yet to finish). I'm quite worried because the dataset we intend to fit contains nearly 1 million samples.

Could you kindly provide a brief estimation of the algorithm's Big-O complexity? Moreover, is there are any potential methods to enhance its performance, such as parallel computing. If yes, could you please guide me on how to implement it?

Best regards,
Thinh

**Comment by jameshay218** [comment]
Hi Thinh,

So sorry for the slow response. We have been working on revisions on the paper accompanying the package and changing the code.

In the worst case it's O(n * t * e * b), where n=number of individuals, t=number of time steps, e=number of exposure types, and b=number of biomarkers. There is some attempted precomputation which collapses "interchangeable" individuals (so n often gets reduced). So it's a slow algorithm in that sense.

We have implemented parallelization as an option, so that should help speed up your large simulation somewhat. This should be possible by setting the `parallel` flag in `runserosim` and setting `n_cores` to the number of cores you'd like to use.

Are you using the `precomputation` flag as TRUE?

Other speed ups are possible by implementing your choice of models in Rcpp. We've added Cpp versions of `antibody_model_monophasic` and `antibody_model_biphasic` (`antibody_model_monophasic_cpp` and `antibody_model_biphasic_cpp`), though the speed ups are only modest due to the overheads of switching between R and Cpp. We could help you implement the other model functions in Rcpp if that would help.

Happy to chat further about whether we can help make `serosim` suitable for your needs -- it's very helpful to hear from users about what features they need.

My email is james.hay@ndm.ox.ac.uk

Best,
James
